spring.datasource.url=jdbc:postgresql://localhost:5432/kmermarket_db
spring.datasource.username=kmermarket_user
spring.datasource.password=motdepasse123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect